-- MySQL Script generated by MySQL Workbench
-- Fri Sep  8 14:28:39 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema valpiok_parkapi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema valpiok_parkapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `valpiok_parkapi` DEFAULT CHARACTER SET utf8 ;
USE `valpiok_parkapi` ;

-- -----------------------------------------------------
-- Table `valpiok_parkapi`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valpiok_parkapi`.`user` (
  `user_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(64) NULL,
  `pass` VARCHAR(255) NULL,
  `email` VARCHAR(127) NULL,
  `name` VARCHAR(127) NULL,
  `registered` DATETIME NULL,
  `status` INT NULL,
  `role` VARCHAR(32) NULL,
  `balance` DECIMAL(10,2) NULL,
  `owner_id` BIGINT(20) NULL,
  `wp_id` BIGINT(20) NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valpiok_parkapi`.`bank_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valpiok_parkapi`.`bank_account` (
  `account_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT(20) NULL,
  `swift_bic` VARCHAR(255) NULL,
  `institution` VARCHAR(255) NULL,
  `intermediary` VARCHAR(255) NULL,
  `account_number` VARCHAR(255) NULL,
  `bank_zip_city` VARCHAR(255) NULL,
  `bank_address` VARCHAR(255) NULL,
  `name` VARCHAR(255) NULL,
  `zip_city` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `iban` VARCHAR(255) NULL,
  PRIMARY KEY (`account_id`),
  CONSTRAINT `fk_a_u`
    FOREIGN KEY (`user_id`)
    REFERENCES `valpiok_parkapi`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valpiok_parkapi`.`parking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valpiok_parkapi`.`parking` (
  `parking_id` INT NOT NULL AUTO_INCREMENT,
  `park_title` VARCHAR(32) NULL,
  `address` VARCHAR(127) NULL,
  `places_qty` INT NULL,
  `rect_min_x` FLOAT(10,6) NULL,
  `rect_min_y` FLOAT(10,6) NULL,
  `rect_max_x` FLOAT(10,6) NULL,
  `rect_max_y` FLOAT(10,6) NULL,
  `center_x` FLOAT(10,6) NULL,
  `center_y` FLOAT(10,6) NULL,
  `park_code` VARCHAR(64) NULL,
  `user_id` BIGINT(20) NOT NULL,
  `parent_id` INT NULL,
  `account_id` INT NULL,
  PRIMARY KEY (`parking_id`),
  INDEX `min_rectangle_idx` (`rect_min_x` ASC, `rect_min_y` ASC, `rect_max_x` ASC, `rect_max_y` ASC),
  INDEX `fk_p_u_idx` (`user_id` ASC),
  INDEX `fk_p_p_idx` (`parent_id` ASC),
  INDEX `fk_p_a_idx` (`account_id` ASC),
  INDEX `center_idx` (`center_x` ASC, `center_y` ASC),
  CONSTRAINT `fk_p_u`
    FOREIGN KEY (`user_id`)
    REFERENCES `valpiok_parkapi`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_p_p`
    FOREIGN KEY (`parent_id`)
    REFERENCES `valpiok_parkapi`.`parking` (`parking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_p_a`
    FOREIGN KEY (`account_id`)
    REFERENCES `valpiok_parkapi`.`bank_account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valpiok_parkapi`.`tariff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valpiok_parkapi`.`tariff` (
  `tariff_id` INT NOT NULL AUTO_INCREMENT,
  `tariff_title` VARCHAR(32) NULL,
  `validity_from` TIME NULL,
  `validity_to` TIME NULL,
  `price` DECIMAL(6,2) NULL,
  `max_time` DECIMAL(4,2) NULL,
  `unit_type` ENUM('min', 'hour') NULL,
  PRIMARY KEY (`tariff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valpiok_parkapi`.`cartype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valpiok_parkapi`.`cartype` (
  `cartype_id` INT NOT NULL AUTO_INCREMENT,
  `cartype_title` VARCHAR(32) NULL,
  PRIMARY KEY (`cartype_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valpiok_parkapi`.`tariff_cartype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valpiok_parkapi`.`tariff_cartype` (
  `tariff_id` INT NOT NULL,
  `cartype_id` INT NOT NULL,
  INDEX `fk_tc_ct_idx` (`cartype_id` ASC),
  INDEX `fk_tc_t_idx` (`tariff_id` ASC),
  CONSTRAINT `fk_t_tct`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `valpiok_parkapi`.`tariff` (`tariff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ct_tct`
    FOREIGN KEY (`cartype_id`)
    REFERENCES `valpiok_parkapi`.`cartype` (`cartype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valpiok_parkapi`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valpiok_parkapi`.`car` (
  `car_id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(32) NULL,
  `cartype_id` INT NOT NULL,
  `user_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`car_id`),
  INDEX `fk_c_сt_idx` (`cartype_id` ASC),
  INDEX `fk_c_u_idx` (`user_id` ASC),
  CONSTRAINT `fk_ct_c`
    FOREIGN KEY (`cartype_id`)
    REFERENCES `valpiok_parkapi`.`cartype` (`cartype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_u_c`
    FOREIGN KEY (`user_id`)
    REFERENCES `valpiok_parkapi`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valpiok_parkapi`.`car_parking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valpiok_parkapi`.`car_parking` (
  `car_parking_id` INT NOT NULL AUTO_INCREMENT,
  `car_id` INT NOT NULL,
  `parking_id` INT NOT NULL,
  `park_from` DATETIME NOT NULL,
  `park_to` DATETIME NULL,
  `status` INT NULL,
  `total` DECIMAL(7,2) NULL,
  PRIMARY KEY (`car_parking_id`),
  INDEX `fk_cp_p_idx` (`parking_id` ASC),
  INDEX `fk_cp_c_idx` (`car_id` ASC),
  CONSTRAINT `fk_cp_c`
    FOREIGN KEY (`car_id`)
    REFERENCES `valpiok_parkapi`.`car` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cp_p`
    FOREIGN KEY (`parking_id`)
    REFERENCES `valpiok_parkapi`.`parking` (`parking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valpiok_parkapi`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valpiok_parkapi`.`token` (
  `token_id` INT NOT NULL AUTO_INCREMENT,
  `token_name` VARCHAR(64) NULL,
  `token_value` VARCHAR(64) NULL,
  `expire` DATETIME NULL,
  `ip` VARCHAR(16) NULL,
  `user_id` BIGINT(20) NULL,
  PRIMARY KEY (`token_id`),
  UNIQUE INDEX `token` (`token_name` ASC, `token_value` ASC),
  INDEX `fk_t_u_idx` (`user_id` ASC),
  CONSTRAINT `fk_t_u`
    FOREIGN KEY (`user_id`)
    REFERENCES `valpiok_parkapi`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `valpiok_parkapi`.`parking_tariff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `valpiok_parkapi`.`parking_tariff` (
  `parking_id` INT NOT NULL,
  `tariff_id` INT NOT NULL,
  INDEX `fk_pt_t_idx` (`tariff_id` ASC),
  INDEX `fk_pt_p_idx` (`parking_id` ASC),
  CONSTRAINT `fk_pt_p`
    FOREIGN KEY (`parking_id`)
    REFERENCES `valpiok_parkapi`.`parking` (`parking_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pt_t`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `valpiok_parkapi`.`tariff` (`tariff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
